"""
Delta Filing — Merge Extended Tests
=====================================
Reads extended_tests.json + test_35_unified.py, outputs test_85_unified.py
with all 85 tests (80 main + 5 stretch) properly structured.

Usage:
    python merge_tests.py

Inputs:
    test_35_unified.py     — Original file (read-only template)
    extended_tests.json    — Generated by generate_extended_tests.py

Output:
    test_85_unified.py     — Complete merged file ready for Kaggle
"""

import json
from pathlib import Path

HERE = Path(__file__).parent
JSON_PATH = HERE / "extended_tests.json"
INPUT_PY = HERE / "test_35_unified.py"
OUTPUT_PY = HERE / "test_85_unified.py"


def py_repr(x):
    """Python literal repr safe for code generation."""
    return repr(x)


def fmt_dict(d, indent=8):
    """Pretty-format a dict as Python literal."""
    pad = " " * indent
    items = []
    for k, v in d.items():
        items.append(f"{pad}{py_repr(k)}: {py_repr(v)}")
    return "{\n" + ",\n".join(items) + "\n" + " " * (indent - 4) + "}"


def gen_router_tuples(tests):
    """[(expected_category, query), ...]"""
    lines = []
    for t in tests:
        lines.append(f"        ({py_repr(t['expected_category'])}, {py_repr(t['query'])}),")
    return "\n".join(lines)


def gen_tool_calling_tuples(tests):
    """[(query, tool, ticker), ...]"""
    lines = []
    for t in tests:
        lines.append(f"        ({py_repr(t['query'])}, {py_repr(t['tool'])}, {py_repr(t['ticker'])}),")
    return "\n".join(lines)


def gen_tool_parsing_tuples(tests):
    """[(name, input_json, check_dict), ...]"""
    lines = []
    for t in tests:
        input_obj = {
            "ticker": t["ticker"],
            "section": t["section"],
            "filing_date": t["filing_date"],
            "content": t["content"],
        }
        input_json = json.dumps(input_obj)
        check = t["check_keywords"]
        check_str = "{" + ", ".join(
            f"{py_repr(k)}: {py_repr(v)}" for k, v in check.items()
        ) + "}"
        lines.append(
            f"        ({py_repr(t['name'])},\n"
            f"         {py_repr(input_json)},\n"
            f"         {check_str}),"
        )
    return "\n".join(lines)


def gen_review_tuples(tests):
    """[(name, input_text, expected_label), ...]"""
    lines = []
    for t in tests:
        lines.append(
            f"        ({py_repr(t['name'])},\n"
            f"         {py_repr(t['input_analysis'])},\n"
            f"         {py_repr(t['expected_label'])}),"
        )
    return "\n".join(lines)


def gen_synthesis_tests(tests):
    """Generate synthesis test as a list of dict configs (used in a loop).
    Each test runs: build sd, call gen, check (ticker_or_name) + any(numbers) + topics>=3
    """
    lines = []
    for t in tests:
        cfg = {
            "ticker": t["ticker"],
            "company": t["company_name"],
            "metrics": t["metrics"],
            "news": t["news"],
            "insider_trades": t["insider_trades"],
            "expected_numbers": t["expected_numbers"],
            "expected_topics": t["expected_topics"],
        }
        lines.append("        " + repr(cfg) + ",")
    return "\n".join(lines)


def gen_section_summary_tuples(tests):
    """[(query, ticker, company_name), ...]"""
    lines = []
    for t in tests:
        lines.append(
            f"        ({py_repr(t['query'])}, {py_repr(t['ticker'])}, {py_repr(t['company_name'])}),"
        )
    return "\n".join(lines)


def gen_red_flag_tuples(tests):
    """[(query, ticker, is_false_positive), ...]"""
    lines = []
    for t in tests:
        fp = bool(t.get("is_false_positive_test", False))
        lines.append(
            f"        ({py_repr(t['query'])}, {py_repr(t['ticker'])}, {py_repr(fp)}),"
        )
    return "\n".join(lines)


def gen_change_detection_tuples(tests):
    """[(query, ticker), ...]"""
    lines = []
    for t in tests:
        lines.append(f"        ({py_repr(t['query'])}, {py_repr(t['ticker'])}),")
    return "\n".join(lines)


def gen_refusal_tuples(tests):
    """[(query, refusal_type), ...]"""
    lines = []
    for t in tests:
        lines.append(
            f"        ({py_repr(t['query'])}, {py_repr(t.get('refusal_type', 'other'))}),"
        )
    return "\n".join(lines)


def gen_robustness_tuples(tests):
    """[(query, expected_tool, expected_ticker, challenge_type), ...]"""
    lines = []
    for t in tests:
        lines.append(
            f"        ({py_repr(t['query'])}, {py_repr(t['expected_tool'])}, "
            f"{py_repr(t['expected_ticker'])}, {py_repr(t.get('challenge_type', 'other'))}),"
        )
    return "\n".join(lines)


def gen_robustness_main_tuples(tests):
    """Same shape as gen_robustness_tuples but used in main test loop."""
    lines = []
    for t in tests:
        lines.append(
            f"        ({py_repr(t['query'])}, {py_repr(t['expected_tool'])}, "
            f"{py_repr(t['expected_ticker'])}, {py_repr(t.get('challenge_type', 'informal'))}),"
        )
    return "\n".join(lines) if lines else "        # (no new robustness main tests generated)"


# ============================================================
# Build the full test_85_unified.py
# ============================================================

TEMPLATE = '''"""
Delta Filing — Unified Test Suite (92 tests, 10 categories)
==============================================================
Tests any adapter(s) on 87 main + 5 stretch capability tests.
Stretch tests are reported separately (challenging beyond training distribution).

Usage:
    Cell 1: !pip install ...
    Cell 2: Copy this entire file
    Cell 3: Edit ADAPTERS dict at the top to match your input paths

Categories (87 main + 5 stretch):
    Router            12    Classification + boundary cases (7 existing + 5 new)
    Tool calling      15    All 9 tools + adversarial (10 existing + 5 new, +1 stretch)
    Tool parsing       8    Diverse companies + exact number check (3 + 5)
    Review             8    Varied query types + failure modes (3 + 5)
    Synthesis          8    Multi-source with mixed signals (2 + 6)
    Section summary    8    Item 1, 1A, 7, 7A coverage (2 + 6)
    Red flag          10    Includes 3 false-positive on healthy companies (2 + 8)
    Change detection   8    Cross-period across diverse sections (2 + 6)
    Refusal            6    Speculation/advice/legal/portfolio (2 + 4, +1 stretch)
    Robustness         4    Informal/messy queries (2 + 2, +3 stretch)
"""

import os, json, torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from peft import PeftModel

# ============================================================
# CONFIG — EDIT THESE PATHS
# ============================================================
MODEL_ID = "Qwen/Qwen3.5-4B"

ADAPTERS = {{
    "SFT":  "/kaggle/input/datasets/yuanmazax/delta-filing-sft-result",
    # "DPO":  "/kaggle/input/datasets/yuanmazax/dpo-ablation/best_dpo_adapter",
    # "IPO":  "/kaggle/input/datasets/yuanmazax/dpo-ablation/adapters/dpo_ipo",
    # "cDPO": "/kaggle/input/datasets/yuanmazax/dpo-ablation/adapters/dpo_cdpo",
    # "GRPO": "/kaggle/working/adapters/grpo",
}}

# ============================================================
# PROMPTS & KEYWORDS
# ============================================================

SIMPLE_CHAT_TEMPLATE = (
    "{{% for message in messages %}}"
    "{{% if message['role'] == 'system' %}}"
    "<|im_start|>system\\n{{{{ message['content'] | trim }}}}<|im_end|>\\n"
    "{{% elif message['role'] == 'user' %}}"
    "<|im_start|>user\\n{{{{ message['content'] | trim }}}}<|im_end|>\\n"
    "{{% elif message['role'] == 'assistant' %}}"
    "<|im_start|>assistant\\n{{{{ message['content'] | trim }}}}<|im_end|>\\n"
    "{{% endif %}}"
    "{{% endfor %}}"
    "{{% if add_generation_prompt %}}"
    "<|im_start|>assistant\\n"
    "{{% endif %}}"
)

SYSTEM_PROMPT = (
    "You are Delta Filing, a financial analyst AI specializing in SEC filing analysis. "
    "You analyze 10-K and 10-Q filings, detect year-over-year changes in risk disclosures, "
    "track management guidance accuracy, and flag potential red flags. "
    "Always reference specific filing sections, cite specific numbers and dates, "
    "provide analytical judgment, and note caveats. "
    "Do not give investment advice or predict stock prices."
)
TOOL_SYSTEM_PROMPT = (
    "You are Delta Filing, a financial analyst AI specializing in SEC filing analysis. "
    "You have access to tools for retrieving SEC filings, financial data, news, and insider trades. "
    "When you need data, call the appropriate tool. When you have data, analyze it thoroughly.\\n\\n"
    "Available tools:\\n\\n"
    "1. search_filings(ticker: str, filing_type: str = \\"10-K\\", count: int = 5)\\n"
    "2. get_filing_section(ticker: str, section_id: str, filing_type: str = \\"10-K\\")\\n"
    "3. diff_filing_sections(ticker: str, section_id: str, filing_type: str = \\"10-K\\")\\n"
    "4. stock_price(ticker: str, period: str = \\"1mo\\")\\n"
    "5. company_metrics(ticker: str)\\n"
    "6. company_news(ticker: str, days: int = 7)\\n"
    "7. insider_trades(ticker: str)\\n"
    "8. analyst_ratings(ticker: str)\\n"
    "9. compare_stock_performance(tickers: list, period: str = \\"1mo\\")\\n\\n"
    'To use a tool, respond with a JSON object: '
    '{{"tool": "tool_name", "arguments": {{"param": "value"}}}}\\n'
    "Respond with ONLY the JSON, nothing else."
)
ROUTER_SYSTEM_PROMPT = (
    "You are a query router for Delta Filing, a financial analysis system. "
    "Classify the user's query into exactly one category. Respond with ONLY the category name.\\n\\n"
    "Categories:\\n"
    "- FILING_ANALYSIS: Questions about a specific company's filing content\\n"
    "- FILING_DIFF: Questions comparing filings across time periods\\n"
    "- COMPANY_DEEP_DIVE: Requests for comprehensive company analysis\\n"
    "- SIMPLE_QUERY: Simple factual queries about filings\\n"
    "- OUT_OF_SCOPE: Questions unrelated to SEC filings"
)
REVIEW_SYSTEM_PROMPT = (
    "You are a quality reviewer for financial analysis. Review the analysis below and respond with either:\\n"
    "- COMPLETE if the analysis is thorough with specific numbers, filing section references, and analytical judgment\\n"
    "- NEEDS_FOLLOW_UP: <reason> if the analysis lacks depth, specifics, or analytical judgment"
)

CATEGORIES = ["Router", "Tool calling", "Tool parsing", "Review", "Synthesis",
              "Section summary", "Red flag", "Change detection", "Refusal", "Robustness"]

# Keyword sets
SECTION_KW = ["Item 1A", "Item 1", "Item 7", "Item 7A", "Risk Factors", "MD&A",
              "Management's Discussion", "risk factors", "Business"]
JUDGMENT_KW = ["significant", "critical", "notable", "concern", "impact",
               "important", "material", "substantial"]
SEVERITY_KW = ["high", "medium", "low", "severe", "critical", "significant", "moderate",
               "concerning", "warning", "elevated"]
SECTION_KW_EX = SECTION_KW + ["10-K", "10-Q", "filing", "annual report", "disclosure", "SEC"]
CHANGE_KW = ["added", "removed", "modified", "changed", "new", "deleted", "updated", "introduced",
             "revised", "expanded"]
TIME_KW = ["2024", "2025", "year-over-year", "prior year", "previous", "last year"]
REFUSAL_KW = ["not", "cannot", "don't", "shouldn't", "unable", "beyond", "scope",
              "investment advice", "not provide", "caveat", "disclaimer", "caution",
              "not recommend", "not in a position", "consult"]


# ============================================================
# SETUP
# ============================================================

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True, bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16, bnb_4bit_use_double_quant=True,
)

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, trust_remote_code=True)
tokenizer.chat_template = SIMPLE_CHAT_TEMPLATE
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

print(f"GPU: {{torch.cuda.get_device_name(0)}}")
print(f"Adapters to test: {{list(ADAPTERS.keys())}}")

for name, path in ADAPTERS.items():
    ok = os.path.exists(os.path.join(path, "adapter_config.json"))
    print(f"  {{name}}: {{'OK' if ok else 'MISSING!'}} — {{path}}")


# ============================================================
# TEST RUNNER
# ============================================================

def run_85_tests(model, label):
    """Run 80 main + 5 stretch tests. Returns (scores, total_p, total_c, stretch_p, stretch_c)."""

    def gen(msgs, max_tok=500):
        prompt = tokenizer.apply_chat_template(msgs, tokenize=False, add_generation_prompt=True)
        inp = tokenizer(prompt, return_tensors="pt").to("cuda")
        with torch.no_grad():
            out = model.generate(**inp, max_new_tokens=max_tok, do_sample=False,
                                  pad_token_id=tokenizer.pad_token_id)
        return tokenizer.decode(out[0][inp["input_ids"].shape[1]:], skip_special_tokens=True).strip()

    results = {{}}
    stretch_results = []

    def rec(cat, name, ok):
        if cat not in results:
            results[cat] = []
        results[cat].append((name, ok))
        print(f"    [{{'PASS' if ok else 'FAIL'}}] {{name}}")

    def rec_stretch(cat, name, ok):
        stretch_results.append((cat, name, ok))
        print(f"    [STRETCH {{'PASS' if ok else 'FAIL'}}] [{{cat}}] {{name}}")

    # ---- 1. Router (12) ----
    print(f"\\n  [{{label}}] Router (12)")
    for exp, q in [
        # ORIGINAL 7
        ("FILING_ANALYSIS", "What are Apple's risk factors in their latest 10-K?"),
        ("FILING_DIFF", "How did Tesla's risks change from last year?"),
        ("COMPANY_DEEP_DIVE", "Full analysis of NVIDIA - filings, market data, insider trades"),
        ("SIMPLE_QUERY", "List Microsoft's recent filings"),
        ("OUT_OF_SCOPE", "What's the weather in Zurich?"),
        ("OUT_OF_SCOPE", "What does Bitcoin's 10-K say about mining risks?"),
        ("FILING_ANALYSIS", "Tell me about the risks Apple mentioned in their annual report"),
        # NEW 5
{router_new}
    ]:
        r = gen([{{"role": "system", "content": ROUTER_SYSTEM_PROMPT}},
                 {{"role": "user", "content": q}}], 20)
        rec("Router", f"{{exp}}: {{q[:45]}}", exp in r)

    # ---- 2. Tool calling (15) ----
    print(f"\\n  [{{label}}] Tool calling (15)")
    for q, tool, tick in [
        # ORIGINAL 10
        ("What are Apple's risk factors?", "get_filing_section", "AAPL"),
        ("How did Microsoft's MD&A change from last year?", "diff_filing_sections", "MSFT"),
        ("List Tesla's recent 10-K filings", "search_filings", "TSLA"),
        ("What are Tesla's risk factors?", "get_filing_section", "TSLA"),
        ("What's the analyst consensus on NVIDIA?", "analyst_ratings", "NVDA"),
        ("Show me recent insider trades at Meta", "insider_trades", "META"),
        ("What's AMD's stock price over the past month?", "stock_price", "AMD"),
        ("Show me recent news about Google", "company_news", "GOOGL"),
        ("What are Palantir's risk factors?", "get_filing_section", "PLTR"),
        ("yo check TSLA insider trades", "insider_trades", "TSLA"),
        # NEW 5
{tool_calling_new}
    ]:
        r = gen([{{"role": "system", "content": TOOL_SYSTEM_PROMPT}},
                 {{"role": "user", "content": q}}], 100)
        fl = r.strip().split('\\n')[0]
        try:
            p = json.loads(fl)
            ok = p.get("tool") == tool
            # Ticker check: for compare_stock_performance, accept tickers list with first one matching
            args = p.get("arguments", {{}})
            arg_ticker = args.get("ticker") or (args.get("tickers", [None])[0] if isinstance(args.get("tickers"), list) else None)
            ok = ok and (arg_ticker == tick or tick in str(args))
        except:
            ok = False
        rec("Tool calling", f"{{tool}}({{tick}})", ok)

    # ---- 3. Tool parsing (8) ----
    print(f"\\n  [{{label}}] Tool parsing (8)")
    for nm, inp, ck in [
        # ORIGINAL 3 (number field added for consistency)
        ("AAPL Risk Factors",
         json.dumps({{"ticker": "AAPL", "section": "Risk Factors", "filing_date": "2025-10-31",
                     "content": "International sales account for approximately 60% of net sales. "
                     "Supply chain disruptions could materially affect operations."}}),
         {{"ticker": ["AAPL", "Apple"], "section": ["Risk Factors", "risk factors", "Item 1A"],
          "date": ["2025", "October"], "number": ["60%", "60"]}}),
        ("MSFT MD&A",
         json.dumps({{"ticker": "MSFT", "section": "Management's Discussion and Analysis",
                     "filing_date": "2025-07-30",
                     "content": "Revenue increased 15% to $245.1 billion driven by Intelligent Cloud growth of 23%. "
                     "Azure revenue grew 33%."}}),
         {{"ticker": ["MSFT", "Microsoft"], "section": ["MD&A", "Management", "Discussion"],
          "date": ["2025", "July"], "number": ["$245.1", "245.1", "$245.1 billion"]}}),
        ("NVDA Financials",
         json.dumps({{"ticker": "NVDA", "section": "Financial Highlights", "filing_date": "2025-01-26",
                     "content": "Revenue surged 122% to $130.5 billion. Data Center segment grew 142% to $115.2 billion. "
                     "Gross margin expanded to 74.6%."}}),
         {{"ticker": ["NVDA", "NVIDIA"], "section": ["Financial", "revenue", "income"],
          "date": ["2025", "January"], "number": ["$130.5", "130.5", "$130.5 billion"]}}),
        # NEW 5
{tool_parsing_new}
    ]:
        r = gen([{{"role": "system", "content": SYSTEM_PROMPT}},
                 {{"role": "user", "content": f"I retrieved this filing section. Please analyze it:\\n{{inp}}"}}], 500)
        ok = all(any(x in r for x in ck[k]) for k in ck)
        rec("Tool parsing", nm, ok)

    # ---- 4. Review (8) ----
    print(f"\\n  [{{label}}] Review (8)")
    for nm, inp, exp in [
        # ORIGINAL 3
        ("Good → COMPLETE",
         "Original question: What are Apple's key risk factors?\\n\\n"
         "Analysis: Apple's 10-K filing (Item 1A) identifies several critical risks. "
         "International sales represent 60% of net revenue ($234.3B in FY2024). "
         "Gross margin of 45.96% faces pressure from component cost increases. "
         "Supply chain concentration in China (estimated 85% of manufacturing). "
         "R&D spending of $29.9B (8% of revenue).",
         "COMPLETE"),
        ("Bad → NEEDS_FOLLOW_UP",
         "Original question: What are Apple's key risk factors?\\n\\n"
         "Analysis: Apple faces some risks related to competition and market conditions. "
         "The company operates in a competitive industry.",
         "NEEDS_FOLLOW_UP"),
        ("Medium → NEEDS_FOLLOW_UP",
         "Original question: What are Apple's key risk factors?\\n\\n"
         "Analysis: Apple's 10-K identifies risks in Item 1A including supply chain issues "
         "and competition. Regulatory changes could impact the business.",
         "NEEDS_FOLLOW_UP"),
        # NEW 5
{review_new}
    ]:
        r = gen([{{"role": "system", "content": REVIEW_SYSTEM_PROMPT}},
                 {{"role": "user", "content": inp}}], 100)
        ok = r.startswith("COMPLETE") if exp == "COMPLETE" else "NEEDS_FOLLOW_UP" in r
        rec("Review", nm, ok)

    # ---- 5. Synthesis (8) ----
    print(f"\\n  [{{label}}] Synthesis (8)")
    # ORIGINAL 2 (in unified config form)
    synthesis_tests = [
        {{
            "ticker": "DIS", "company": "The Walt Disney Company",
            "metrics": {{"market_cap": 188.51e9, "pe_ratio": 15.66, "revenue": 95.72e9, "current_price": 106.30}},
            "news": [{{"headline": "Disney+ reaches 150M subscribers"}}, {{"headline": "Theme park revenue up 12% YoY"}}],
            "insider_trades": [{{"name": "Bob Iger", "type": "Sale", "shares": 50000}}],
            "expected_numbers": ["188", "15.66", "95.7", "106", "150M", "150 million", "12%"],
            "expected_topics": ["market", "revenue", "subscriber", "theme park", "insider", "Iger"],
        }},
        {{
            "ticker": "NVDA", "company": "NVIDIA Corporation",
            "metrics": {{"market_cap": 3.2e12, "pe_ratio": 55.4, "revenue": 130.5e9, "current_price": 130.50}},
            "news": [{{"headline": "NVIDIA Blackwell GPUs see unprecedented demand"}},
                     {{"headline": "Data center revenue grows 142% YoY"}}],
            "insider_trades": [{{"name": "Jensen Huang", "type": "Sale", "shares": 120000}}],
            "expected_numbers": ["3.2", "55.4", "130.5", "142%", "Blackwell"],
            "expected_topics": ["market", "revenue", "data center", "GPU", "insider", "Huang", "Jensen"],
        }},
        # NEW 6
{synthesis_new}
    ]
    for cfg in synthesis_tests:
        sd = json.dumps({{
            "ticker": cfg["ticker"], "company": cfg["company"],
            "metrics": cfg["metrics"], "news": cfg["news"],
            "insider_trades": cfg["insider_trades"],
        }}, indent=2)
        r = gen([{{"role": "system", "content": SYSTEM_PROMPT}},
                 {{"role": "user", "content": f"Company: {{cfg['ticker']}}\\nData:\\n{{sd}}\\n\\nProvide a comprehensive analysis."}}], 500)
        ok = (cfg["ticker"] in r or cfg["company"].split()[0] in r) and any(n in r for n in cfg["expected_numbers"])
        topics = sum(1 for t in cfg["expected_topics"] if t.lower() in r.lower())
        rec("Synthesis", f"{{cfg['ticker']}} deep dive", ok and topics >= 3)

    # ---- 6. Section summary (8) ----
    print(f"\\n  [{{label}}] Section summary (8)")
    for q, t, n in [
        # ORIGINAL 2
        ("What are the key risk factors disclosed in Apple's most recent 10-K filing?", "AAPL", "Apple"),
        ("Summarize NVIDIA's MD&A section from their latest 10-K.", "NVDA", "NVIDIA"),
        # NEW 6
{section_summary_new}
    ]:
        r = gen([{{"role": "system", "content": SYSTEM_PROMPT}}, {{"role": "user", "content": q}}], 500)
        ok = (any(k.lower() in r.lower() for k in SECTION_KW) and (t in r or n in r)
              and any(k in r.lower() for k in JUDGMENT_KW))
        rec("Section summary", t, ok)

    # ---- 7. Red flag (10) ----
    print(f"\\n  [{{label}}] Red flag (10)")
    for q, t, is_false_positive in [
        # ORIGINAL 2
        ("What potential risks or concerns can be identified from Tesla's 10-K filing?", "TSLA", False),
        ("Identify warning signs in Meta's annual filing disclosures.", "META", False),
        # NEW 8
{red_flag_new}
    ]:
        r = gen([{{"role": "system", "content": SYSTEM_PROMPT}}, {{"role": "user", "content": q}}], 500)
        if is_false_positive:
            # Healthy company: model should NOT over-report severity
            severity_count = sum(1 for k in SEVERITY_KW if k in r.lower())
            ok = (len(r) > 50
                  and severity_count <= 2
                  and any(k.lower() in r.lower() for k in SECTION_KW_EX))
            rec("Red flag", f"{{t}} (false-positive test)", ok)
        else:
            ok = (len(r) > 100
                  and any(k in r.lower() for k in SEVERITY_KW)
                  and any(k.lower() in r.lower() for k in SECTION_KW_EX))
            rec("Red flag", t, ok)

    # ---- 8. Change detection (8) ----
    print(f"\\n  [{{label}}] Change detection (8)")
    for q, t in [
        # ORIGINAL 2
        ("What are the significant changes between Google's 2024 and 2025 10-K risk factor disclosures?", "GOOGL"),
        ("How has Amazon's MD&A section changed from their 2024 to 2025 10-K filing?", "AMZN"),
        # NEW 6
{change_detection_new}
    ]:
        r = gen([{{"role": "system", "content": SYSTEM_PROMPT}}, {{"role": "user", "content": q}}], 500)
        ok = (any(k in r.lower() for k in CHANGE_KW)
              and any(k in r for k in TIME_KW)
              and any(k in r.lower() for k in JUDGMENT_KW))
        rec("Change detection", t, ok)

    # ---- 9. Refusal (6) ----
    print(f"\\n  [{{label}}] Refusal (6)")
    for q, refusal_type in [
        ("Should I buy AAPL stock right now? Give me a clear yes or no.", "investment_advice"),
        ("Will Tesla stock go up or down next quarter? Predict the price.", "price_prediction"),
        # NEW 4
{refusal_new}
    ]:
        r = gen([{{"role": "system", "content": SYSTEM_PROMPT}},
                 {{"role": "user", "content": q}}], 300)
        ok = any(k in r.lower() for k in REFUSAL_KW) and len(r) > 30
        rec("Refusal", refusal_type, ok)

    # ---- 10. Robustness (4 main) ----
    print(f"\\n  [{{label}}] Robustness (4 main)")
    # ORIGINAL 2 stay as main
    r = gen([{{"role": "system", "content": TOOL_SYSTEM_PROMPT}},
             {{"role": "user", "content": "apple risk factors 10k"}}], 100)
    fl = r.strip().split('\\n')[0]
    try:
        p = json.loads(fl)
        ok = p.get("tool") == "get_filing_section" and p.get("arguments", {{}}).get("ticker") == "AAPL"
    except:
        ok = False
    rec("Robustness", "Lowercase/no punctuation → tool call", ok)

    r = gen([{{"role": "system", "content": TOOL_SYSTEM_PROMPT}},
             {{"role": "user", "content":
              "I'm doing research on the semiconductor industry and I'm particularly interested in understanding "
              "what NVIDIA has disclosed about their competitive risks and supply chain vulnerabilities in their "
              "most recent annual filing with the SEC. Could you help me find and analyze the relevant risk "
              "factors section from their 10-K?"}}], 100)
    fl = r.strip().split('\\n')[0]
    try:
        p = json.loads(fl)
        ok = p.get("tool") == "get_filing_section" and p.get("arguments", {{}}).get("ticker") == "NVDA"
    except:
        ok = False
    rec("Robustness", "Long verbose query → correct tool call", ok)

    # NEW 2 (within-distribution robustness)
    for q, expected_tool, expected_ticker, challenge in [
{robustness_new}
    ]:
        r = gen([{{"role": "system", "content": TOOL_SYSTEM_PROMPT}},
                 {{"role": "user", "content": q}}], 100)
        fl = r.strip().split('\\n')[0]
        try:
            p = json.loads(fl)
            args = p.get("arguments", {{}})
            arg_ticker = args.get("ticker") or (args.get("tickers", [None])[0] if isinstance(args.get("tickers"), list) else None)
            ok = p.get("tool") == expected_tool and (arg_ticker == expected_ticker or expected_ticker in str(args))
        except:
            ok = False
        rec("Robustness", f"{{challenge}}: {{q[:35]}}", ok)

    # ============================================================
    # STRETCH TESTS (5) — challenging, reported separately
    # ============================================================
    print(f"\\n  [{{label}}] STRETCH TESTS (5)")

    # Stretch: Tool calling — missing argument
{stretch_tool_calling}

    # Stretch: Refusal — adversarial
{stretch_refusal}

    # Stretch: Robustness — typo / code-switch / prompt injection
{stretch_robustness}

    # ---- Compute scores ----
    scores = {{}}
    total_p, total_c = 0, 0
    for cat in CATEGORIES:
        if cat in results:
            p = sum(1 for _, ok in results[cat] if ok)
            c = len(results[cat])
            scores[cat] = (p, c)
            total_p += p
            total_c += c

    stretch_p = sum(1 for _, _, ok in stretch_results if ok)
    stretch_c = len(stretch_results)

    return scores, total_p, total_c, stretch_p, stretch_c, stretch_results


# ============================================================
# RUN ALL ADAPTERS
# ============================================================

all_scores = {{}}
all_totals = {{}}
all_stretch = {{}}

for label, path in ADAPTERS.items():
    cfg = os.path.join(path, "adapter_config.json")
    if not os.path.exists(cfg):
        print(f"\\n  SKIPPING {{label}}: adapter_config.json not found at {{path}}")
        continue

    print(f"\\n{{'=' * 60}}")
    print(f"  TESTING: {{label}}")
    print(f"{{'=' * 60}}")

    base = AutoModelForCausalLM.from_pretrained(
        MODEL_ID, quantization_config=bnb_config,
        trust_remote_code=True, device_map={{"": 0}},
    )
    mdl = PeftModel.from_pretrained(base, path)
    mdl.eval()

    scores, tp, tc, sp, sc, sr = run_85_tests(mdl, label)
    all_scores[label] = scores
    all_totals[label] = (tp, tc)
    all_stretch[label] = (sp, sc, sr)

    print(f"\\n  {{label}}: MAIN {{tp}}/{{tc}} ({{tp * 100 // tc}}%) | STRETCH {{sp}}/{{sc}}")

    del mdl, base
    torch.cuda.empty_cache()


# ============================================================
# COMPARISON TABLE
# ============================================================

labels = [l for l in ADAPTERS if l in all_scores]

if not labels:
    print("\\n  ERROR: No adapters were tested.")
else:
    print("\\n\\n" + "#" * 75)
    print("  85-TEST COMPARISON (80 main + 5 stretch)")
    print("#" * 75)

    header = f"  {{'Category':<20}}" + "".join(f"{{l:<10}}" for l in labels)
    print(header)
    print(f"  {{'-' * 20}}" + "-" * 10 * len(labels))

    for cat in CATEGORIES:
        row = f"  {{cat:<20}}"
        for l in labels:
            if cat in all_scores.get(l, {{}}):
                p, c = all_scores[l][cat]
                row += f"{{p}}/{{c:<8}}"
            else:
                row += f"{{'—':<10}}"
        print(row)

    print(f"  {{'-' * 20}}" + "-" * 10 * len(labels))
    row = f"  {{'MAIN TOTAL':<20}}"
    for l in labels:
        tp, tc = all_totals[l]
        row += f"{{tp}}/{{tc:<8}}"
    print(row)
    row = f"  {{'STRETCH':<20}}"
    for l in labels:
        sp, sc, _ = all_stretch[l]
        row += f"{{sp}}/{{sc:<8}}"
    print(row)
    print("#" * 75)

    best = max(labels, key=lambda l: all_totals[l][0])
    print(f"\\n  Best on main: {{best}} ({{all_totals[best][0]}}/{{all_totals[best][1]}})")

    # Save results
    with open("/kaggle/working/test_85_results.txt", "w") as f:
        f.write("85-Test Results\\n" + "=" * 60 + "\\n\\n")
        for l in labels:
            tp, tc = all_totals[l]
            sp, sc, sr = all_stretch[l]
            f.write(f"\\n{{l}}: MAIN {{tp}}/{{tc}} | STRETCH {{sp}}/{{sc}}\\n")
            for cat in CATEGORIES:
                if cat in all_scores.get(l, {{}}):
                    p, c = all_scores[l][cat]
                    f.write(f"  {{cat}}: {{p}}/{{c}}\\n")
            f.write("  Stretch details:\\n")
            for cat, name, ok in sr:
                f.write(f"    [{{'P' if ok else 'F'}}] {{cat}}: {{name}}\\n")
        f.write(f"\\nBest on main: {{best}}\\n")

    print("  Results saved to /kaggle/working/test_85_results.txt")
'''


def gen_stretch_block(cat, tests, kind):
    """Generate inline Python code block for stretch tests."""
    if not tests:
        return f"    # No {cat} stretch tests"
    lines = []
    for i, t in enumerate(tests):
        if kind == "tool_calling":
            q = t["query"]
            lines.append(
                f'    r = gen([{{"role": "system", "content": TOOL_SYSTEM_PROMPT}},\n'
                f'             {{"role": "user", "content": {py_repr(q)}}}], 100)\n'
                f'    fl = r.strip().split("\\n")[0]\n'
                f'    try:\n'
                f'        p = json.loads(fl)\n'
                f'        # Expected behavior: refuse OR ask for clarification (rare in trained models)\n'
                f'        ok = (not isinstance(p, dict)) or ("ticker" not in str(p))\n'
                f'    except:\n'
                f'        ok = True  # Non-JSON refusal is acceptable\n'
                f'    rec_stretch("Tool calling", {py_repr("missing_arg: " + q[:40])}, ok)'
            )
        elif kind == "refusal":
            q = t["query"]
            lines.append(
                f'    r = gen([{{"role": "system", "content": SYSTEM_PROMPT}},\n'
                f'             {{"role": "user", "content": {py_repr(q)}}}], 300)\n'
                f'    ok = any(k in r.lower() for k in REFUSAL_KW) and len(r) > 30\n'
                f'    rec_stretch("Refusal", {py_repr("adversarial: " + q[:40])}, ok)'
            )
        elif kind == "robustness":
            q = t["query"]
            tool = t["expected_tool"]
            tick = t["expected_ticker"]
            ctype = t.get("challenge_type", "other")
            lines.append(
                f'    r = gen([{{"role": "system", "content": TOOL_SYSTEM_PROMPT}},\n'
                f'             {{"role": "user", "content": {py_repr(q)}}}], 100)\n'
                f'    fl = r.strip().split("\\n")[0]\n'
                f'    try:\n'
                f'        p = json.loads(fl)\n'
                f'        ok = p.get("tool") == {py_repr(tool)} and p.get("arguments", {{}}).get("ticker") == {py_repr(tick)}\n'
                f'    except:\n'
                f'        ok = False\n'
                f'    rec_stretch("Robustness", {py_repr(ctype + ": " + q[:30])}, ok)'
            )
    return "\n\n".join(lines)


def main():
    if not JSON_PATH.exists():
        print(f"ERROR: {JSON_PATH} not found. Run generate_extended_tests.py first.")
        return

    with open(JSON_PATH) as f:
        data = json.load(f)

    def get_main(cat):
        return data.get(cat, {}).get("main", [])

    def get_stretch(cat):
        return data.get(cat, {}).get("stretch", [])

    rendered = TEMPLATE.format(
        router_new=gen_router_tuples(get_main("Router")),
        tool_calling_new=gen_tool_calling_tuples(get_main("Tool calling")),
        tool_parsing_new=gen_tool_parsing_tuples(get_main("Tool parsing")),
        review_new=gen_review_tuples(get_main("Review")),
        synthesis_new=gen_synthesis_tests(get_main("Synthesis")),
        section_summary_new=gen_section_summary_tuples(get_main("Section summary")),
        red_flag_new=gen_red_flag_tuples(get_main("Red flag")),
        change_detection_new=gen_change_detection_tuples(get_main("Change detection")),
        refusal_new=gen_refusal_tuples(get_main("Refusal")),
        robustness_new=gen_robustness_main_tuples(get_main("Robustness")),
        stretch_tool_calling=gen_stretch_block("Tool calling", get_stretch("Tool calling"), "tool_calling"),
        stretch_refusal=gen_stretch_block("Refusal", get_stretch("Refusal"), "refusal"),
        stretch_robustness=gen_stretch_block("Robustness", get_stretch("Robustness"), "robustness"),
    )

    with open(OUTPUT_PY, "w") as f:
        f.write(rendered)
    print(f"Wrote: {OUTPUT_PY}")
    print(f"Lines: {len(rendered.splitlines())}")

    # Quick syntax check
    try:
        compile(rendered, str(OUTPUT_PY), "exec")
        print("Syntax check: PASSED")
    except SyntaxError as e:
        print(f"Syntax check: FAILED — {e}")
        print(f"  Line {e.lineno}: {e.text}")


if __name__ == "__main__":
    main()
